services: 
  mvmtsp-app: 
    build: . 
    image: dgeorgiadishua/glpk-python3:mvmtsp 

    volumes: 
     - ./:/workspace 
     - venv_data:/opt/venv 

    environment: 
     - VENV_PATH=/opt/venv


    ipc: host 
    shm_size: "1gb" 

    command: >
      bash -lc "
        set -e; 
        python3 -V; 
        glpsol --version; 

        if [ ! -f \"$$VENV_PATH/bin/python\" ]; then
          echo 'Creating venv in '\"$$VENV_PATH\"; 
          python3 -m venv \"$$VENV_PATH\"; 
          # FIX: Call the VENV pip explicitly to install inside the venv
          \"$$VENV_PATH/bin/pip\" install --upgrade pip;
          \"$$VENV_PATH/bin/pip\" install -e .; 
        fi;

        \"$$VENV_PATH/bin/python\" execution_script.py
      " 


volumes: 
  venv_data: 
